package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"time"
)

func (v *monstre) charturn(m *personnage) {
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                        ,===:'.,_________'-._   ")
	fmt.Println("                                          ':.'---.__         '-._      ")
	fmt.Println("                                              ':.     '--.         '. ")
	fmt.Println("                                                \\.        '.         '. ")
	fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
	fmt.Println("     __,|**|,__                     (,'     ''\\  \\.   ,--.___'.'     ")
	fmt.Println("    (__ '--'  _)                   ,  ,'  ,--.  ', \\.;'         ' ")
	fmt.Println("    |^^|.  ._/ \\                  '{*, {    |  :   \\;    ")
	fmt.Println("    |__|    |  ||                   |,,'    /  /    //       ")
	fmt.Println("  <===========]OO                   |;;    /  ,' ,-//.    ,---.      ,  ")
	fmt.Println("       ||---||                      o;'   /  ,' /  _  |  /  _  |   ,'/ ")
	fmt.Println("       ||   ||                            |  ''  /  | ''  /  | '.'  / ")
	fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
	fmt.Println("____________________________________________________________________")
	fmt.Println("____________________________________________________________________")
	fmt.Println("Attaque (4)")
	fmt.Println("Inventaire (5)")
	scan_r := bufio.NewScanner(os.Stdin)
	scan_r.Scan()
	nom_r, _ := strconv.Atoi(scan_r.Text())
	if nom_r == 5 {
		fmt.Println("Inventaire:", m.inventaire)
		fmt.Println("Utiliser une potion de soin (1)")
		fmt.Println("Utiliser une potion de poison (2)")
		fmt.Println("Retour (10)")
		scanner33 := bufio.NewScanner(os.Stdin)
		scanner33.Scan()
		nom_f, _ := strconv.Atoi(scanner33.Text())
		if nom_f == 10 {
			v.charturn(m)
		}
		if nom_f == 1 {
			m.takePot()
			time.Sleep(1 * time.Second)
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			v.charturn(m)
		}
		if nom_f == 2 {
			m.poisonPot()
			time.Sleep(1 * time.Second)
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			v.charturn(m)
		}
		if nom_f == 7 {
			m.poisonPot()
			time.Sleep(2 * time.Second)
			m.Wasted()
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			v.charturn(m)
		}
	}
	if nom_r == 4 {
		fmt.Println("Attaque à l'épée  (6)")
		fmt.Println("Boule de feu  (7)")
		scan_r := bufio.NewScanner(os.Stdin)
		scan_r.Scan()
		no_r, _ := strconv.Atoi(scan_r.Text())
		if no_r == 6 {
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			fmt.Println("")
			fmt.Println("")
			fmt.Println("                                        ,===:'.,_________'-._   ")
			fmt.Println("                                          ':.'---.__         '-._      ")
			fmt.Println("                                              ':.     '--.         '. ")
			fmt.Println("                                                \\.        '.         '. ")
			fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
			fmt.Println("     __,|**|,__                     (,'     ''\\  \\.   ,--.___'.'     ")
			fmt.Println("    (__ '--'  _)                   ,  ,'  ,--.  ', \\.;'         ' ")
			fmt.Println("    |^^|.  ._/ \\                  '{*, {    |  :   \\;    ")
			fmt.Println("    |__|    |  ||                   |,,'    /  /    //       ")
			fmt.Println("  <===========]OO                   |;;    /  ,' ,-//.    ,---.      ,  ")
			fmt.Println("       ||---||                      o;'   /  ,' /  _  |  /  _  |   ,'/ ")
			fmt.Println("       ||   ||                            |  ''  /  | ''  /  | '.'  / ")
			fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
			fmt.Println("____________________________________________________________________")
			fmt.Println("____________________________________________________________________")
			time.Sleep(200 * time.Millisecond)
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			fmt.Println("")
			fmt.Println("")
			fmt.Println("                                        ,===:'.,_________'-._   ")
			fmt.Println("                                          ':.'---.__         '-._      ")
			fmt.Println("                                              ':.     '--.         '. ")
			fmt.Println("                                                \\.        '.         '. ")
			fmt.Println("          (.--.)                        (,,(,    \\.         '.   ____,-'., ")
			fmt.Println("        __,|**|,__                  (,'     ''\\  \\.   ,--.___'.'     ")
			fmt.Println("       (__ '--'  _)                ,  ,'  ,--.  ', \\.;'         ' ")
			fmt.Println("       |^^|.  ._/ \\               '{*, {    |  :   \\;    ")
			fmt.Println("       |__|    |  ||                |,,'    /  /    //       ")
			fmt.Println("     <===========]OO                |;;    /  ,' ,-//.    ,---.      ,  ")
			fmt.Println("         _||---\\                   o;'   /  ,' /  _  |  /  _  |   ,'/ ")
			fmt.Println("        H__|     \\                       |  ''  /  | ''  /  | '.'  / ")
			fmt.Println("_________________HH_______________________'____,'___'.__,'___'.__,'  ")
			fmt.Println("____________________________________________________________________")
			fmt.Println("____________________________________________________________________")
			time.Sleep(200 * time.Millisecond)
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			fmt.Println("")
			fmt.Println("")
			fmt.Println("                                        ,===:'.,_________'-._   ")
			fmt.Println("                                          ':.'---.__         '-._      ")
			fmt.Println("                                              ':.     '--.         '. ")
			fmt.Println("                                                \\.        '.         '. ")
			fmt.Println("                   (.--.)               (,,(,    \\.         '.   ____,-'., ")
			fmt.Println("                 __,|**|,__         (,'     ''\\  \\.   ,--.___'.'     ")
			fmt.Println("                (__ '--'  _)       ,  ,'  ,--.  ', \\.;'         ' ")
			fmt.Println("                |^^|.  ._/ \\      '{*, {    |  :   \\;    ")
			fmt.Println("                |__|    |  ||       |,,'    /  /    //       ")
			fmt.Println("              <===========]OO       |;;    /  ,' ,-//.    ,---.      ,  ")
			fmt.Println("                   \\---\\          o;'   /  ,' /  _  |  /  _  |   ,'/ ")
			fmt.Println("                   ||    ||             |  ''  /  | ''  /  | '.'  / ")
			fmt.Println("___________________HH__  HH______________'____,'___'.__,'___'.__,'  ")
			fmt.Println("____________________________________________________________________")
			fmt.Println("____________________________________________________________________")
			time.Sleep(300 * time.Millisecond)
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			fmt.Println("")
			fmt.Println("")
			fmt.Println("                                        ,===:'.,_________'-._   ")
			fmt.Println("                                          ':.'---.__         '-._      ")
			fmt.Println("                                              ':.     '--.         '. ")
			fmt.Println("             <============]OO                   \\.        '.         '. ")
			fmt.Println("                    (.--.) ||            (,,(,   \\.         '.   ____,-'., ")
			fmt.Println("                  __,|**|,_||        (,'     ''\\ \\.   ,--.___'.'     ")
			fmt.Println("                 (__ '--'  //      ,  ,'  ,--.  ', \\.;'         ' ")
			fmt.Println("                 |^^|.  ._/        '{*, {    |  :   \\;    ")
			fmt.Println("                 |__|    |          |,,'    /  /    //       ")
			fmt.Println("                   (--[]--)         |;;    /  ,' ,-//.    ,---.      ,  ")
			fmt.Println("                   ||----||         o;'   /  ,' /  _  |  /  _  |   ,'/ ")
			fmt.Println("                   ||    ||             |  ''  /  | ''  /  | '.'  / ")
			fmt.Println("___________________HH__  HH______________'____,'___'.__,'___'.__,'  ")
			fmt.Println("____________________________________________________________________")
			fmt.Println("____________________________________________________________________")
			time.Sleep(300 * time.Millisecond)
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			fmt.Println("")
			fmt.Println("")
			fmt.Println("                                        ,===:'.,_________'-._   ")
			fmt.Println("                            █             ':.'---.__         '-._      ")
			fmt.Println("                             ███              ':.     '--.         '. ")
			fmt.Println("                              █████             \\.        '.         '. ")
			fmt.Println("                    (.--.)     ████████  (,,(,   \\.         '.   ____,-'., ")
			fmt.Println("                  __,|**|,__     █████████   ''\\ \\.   ,--.___'.'     ")
			fmt.Println("                 (__ '--'  _)     ████8█████-.  ', \\.;'         ' ")
			fmt.Println("                 |^^|.  ._/||      █████████ |  :   \\;    ")
			fmt.Println("                 |__|    | ||       ███████ /  /    //       ")
			fmt.Println("                   (--[]--)OO[=======█████ /  ,' ,-//.    ,---.      ,  ")
			fmt.Println("                   ||----||         o;'   /  ,' /  _  |  /  _  |   ,'/ ")
			fmt.Println("                   ||    ||             |  ''  /  | ''  /  | '.'  / ")
			fmt.Println("___________________HH__  HH______________'____,'___'.__,'___'.__,'  ")
			fmt.Println("____________________________________________________________________")
			fmt.Println("____________________________________________________________________")
			time.Sleep(300 * time.Millisecond)
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			fmt.Println("")
			fmt.Println("")
			fmt.Println("                                        ,===:'.,_________'-._   ")
			fmt.Println("                                          ':.'---.__         '-._      ")
			fmt.Println("                                              ':.     '--.         '. ")
			fmt.Println("                                                \\.        '.         '. ")
			fmt.Println("                    (.--.)              (,,(,    \\.         '.   ____,-'., ")
			fmt.Println("                  __,|**|,__        (,'     ''\\  \\.   ,--.___'.'     ")
			fmt.Println("                 (__ '--'  _)      ,  ,'  ,--.  ', \\.;'         ' ")
			fmt.Println("                 |^^|.  ._/ \\     X{X, {    |  :   \\;    ")
			fmt.Println("                 |__|    |  ||      |,,'    /  /    //       ")
			fmt.Println("              <===========]OO       |;;    /  ,' ,-//.    ,---.      ,  ")
			fmt.Println("                   ||----||          o;'   /  ,' /  _  |  /  _  |   ,'/ ")
			fmt.Println("                   ||    ||             |  ''  /  | ''  /  | '.'  / ")
			fmt.Println("___________________HH__  HH______________'____,'___'.__,'___'.__,'  ")
			fmt.Println("____________________________________________________________________")
			fmt.Println("____________________________________________________________________")
			v.hpactuels_monstre = v.hpactuels_monstre - m.attaque
			fmt.Println("Vous infligez ", m.attaque, " dégats, il ne reste plus que", v.hpactuels_monstre, "points de vie au dragon")
			time.Sleep(1500 * time.Millisecond)
			os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
			m.dragonpattern(v)
		}
		if no_r == 7 {
			n := 0
			for i := 0; i <= len(m.sorts)-1; i++ {
				if m.magie >= 8 {
					if m.sorts[i] == "Boule de feu" {
						n += 1
						m.sorts[i] = "Emplacement vide"
						m.removesorts()
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                        ,===:'.,_________'-._   ")
						fmt.Println("                                          ':.'---.__         '-._      ")
						fmt.Println("                                              ':.     '--.         '. ")
						fmt.Println("                                                \\.        '.         '. ")
						fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
						fmt.Println("     __,|**|,__                     (,'     ''\\  \\.   ,--.___'.'     ")
						fmt.Println("    (__ '--'  _)                   ,  ,'  ,--.  ', \\.;'         ' ")
						fmt.Println("    |^^|.  ._/ \\                  '{*, {    |  :   \\;    ")
						fmt.Println("    |__|    |  ||                   |,,'    /  /    //       ")
						fmt.Println("  <===========]OO                   |;;    /  ,' ,-//.    ,---.      ,  ")
						fmt.Println("       ||---||                      o;'   /  ,' /  _  |  /  _  |   ,'/ ")
						fmt.Println("       ||   ||                            |  ''  /  | ''  /  | '.'  / ")
						fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						time.Sleep(600 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                        ,===:'.,_________'-._   ")
						fmt.Println("                                          ':.'---.__         '-._      ")
						fmt.Println("                                              ':.     '--.         '. ")
						fmt.Println("                                                \\.        '.         '. ")
						fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
						fmt.Println("     __,|**|,______                 (,'     ''\\  \\.   ,--.___'.'     ")
						fmt.Println("    (__ '--'  _--OO__              ,  ,'  ,--.  ', \\.;'         ' ")
						fmt.Println("    |^^|.  ._/     ||              '{*, {    |  :   \\;    ")
						fmt.Println("    |__|    |      ||               |,,'    /  /    //       ")
						fmt.Println("      (--[]--)     ||               |;;    /  ,' ,-//.    ,---.      ,  ")
						fmt.Println("       ||---||     ||               o;'   /  ,' /  _  |  /  _  |   ,'/ ")
						fmt.Println("       ||   ||     V                      |  ''  /  | ''  /  | '.'  / ")
						fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						time.Sleep(600 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                        ,===:'.,_________'-._   ")
						fmt.Println("                                          ':.'---.__         '-._      ")
						fmt.Println("                                               ':.     '--.         '. ")
						fmt.Println("                                                \\.        '.         '. ")
						fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
						fmt.Println("     __,|**|,________               (,'     ''\\  \\.   ,--.___'.'     ")
						fmt.Println("    (__ '--'  _____ |              ,  ,'  ,--.  ', \\.;'         ' ")
						fmt.Println("    |^^|.  ._/     OO              '{*, {    |  :   \\;    ")
						fmt.Println("    |__|    |     _||_              |,,'    /  /    //       ")
						fmt.Println("      (--[]--)     ||               |;;    /  ,' ,-//.    ,---.      ,  ")
						fmt.Println("       ||---||     ||               o;'   /  ,' /  _  |  /  _  |   ,'/ ")
						fmt.Println("       ||   ||  . .|| .                   |  ''  /  | ''  /  | '.'  / ")
						fmt.Println("_______HH___HH_____||..___________________'____,'___'.__,'___'.__,'  ")
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						time.Sleep(600 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                        ,===:'.,_________'-._   ")
						fmt.Println("                                          ':.'---.__         '-._      ")
						fmt.Println("             \\|/                              ':.     '--.         '. ")
						fmt.Println("            --OO                                \\.        '.         '. ")
						fmt.Println("       (.--.) ||                        (,,(,    \\.         '.   ____,-'., ")
						fmt.Println("     __,|**|,_||                    (,'     ''\\  \\.   ,--.___'.'     ")
						fmt.Println("    (__ '--'   )                   ,  ,'  ,--.  ', \\.;'         ' ")
						fmt.Println("    |^^|.  ._/     TT              '{*, {    |  :   \\;    ")
						fmt.Println("    |__|    |     _||_              |,,'    /  /    //       ")
						fmt.Println("      (--[]--)     ||               |;;    /  ,' ,-//.    ,---.      ,  ")
						fmt.Println("       ||---||     ||               o;'   /  ,' /  _  |  /  _  |   ,'/ ")
						fmt.Println("       ||   ||     ||                     |  ''  /  | ''  /  | '.'  / ")
						fmt.Println("_______HH___HH_____||_____________________'____,'___'.__,'___'.__,'  ")
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						time.Sleep(600 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                        ,===:'.,_________'-._   ")
						fmt.Println("                                          ':.'---.__         '-._      ")
						fmt.Println("                                              ':.     '--.         '. ")
						fmt.Println("                                                \\.        '.         '. ")
						fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
						fmt.Println("     __,|**|,_______", Red+"████████████"+Reset, "\\.   ,--.___'.'     ")
						fmt.Println("    (__ '--'  ______", Red+"██████████"+Reset, "   \\.;'         ' ")
						fmt.Println("    |^^|.  ._/     T", Red+"██████████"+Reset, ":   \\;    ")
						fmt.Println("    |__|    |     _||_              |,,'    /  /    //       ")
						fmt.Println("      (--[]--)     ||               |;;    /  ,' ,-//.    ,---.      ,  ")
						fmt.Println("       ||---||     ||               o;'   /  ,' /  _  |  /  _  |   ,'/ ")
						fmt.Println("       ||   ||     ||                     |  ''  /  | ''  /  | '.'  / ")
						fmt.Println("_______HH___HH_____||_____________________'____,'___'.__,'___'.__,'  ")
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						time.Sleep(600 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                      ", Red+"██████████████████████"+Reset)
						fmt.Println("                                   ", Red+"█████████████████████████"+Reset)
						fmt.Println("                                 ", Red+"███████████████████████████"+Reset)
						fmt.Println("                              ", Red+"██████████████████████████████"+Reset)
						fmt.Println("       (.--.)             ", Red+"███OO█████████████████████████████"+Reset)
						fmt.Println("     __,|**|,_______", Red+"████████████████████████████████████████"+Reset)
						fmt.Println("    (__ '--'  ______", Red+"████████████████████████████████████████"+Reset)
						fmt.Println("    |^^|.  ._/     T", Red+"████████████████████████████████████████"+Reset)
						fmt.Println("    |__|    |     _||_    ", Red+"██████████████████████████████████"+Reset)
						fmt.Println("      (--[]--)     ||         ", Red+"██████████████████████████████"+Reset)
						fmt.Println("       ||---||     ||           ", Red+"████████████████████████████"+Reset)
						fmt.Println("       ||   ||     ||              ", Red+"█████████████████████████"+Reset)
						fmt.Println("_______HH___HH_____||_________________", Red+"██████████████████████"+Reset)
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						time.Sleep(2000 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                        ,===:'.,_________'-._   ")
						fmt.Println("                                          ':.'---.__         '-._      ")
						fmt.Println("                                               ':.     '--.         '. ")
						fmt.Println("                                                \\.        '.         '. ")
						fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
						fmt.Println("     __,|**|,________               (,'     ''\\  \\.   ,--.___'.'     ")
						fmt.Println("    (__ '--'  _____ |              ,  ,'  ,--.  ', \\.;'         ' ")
						fmt.Println("    |^^|.  ._/     OO              '{*, {    |  :   \\;    ")
						fmt.Println("    |__|    |     _||_              |,,'    /  /    //       ")
						fmt.Println("      (--[]--)     ||               |;;    /  ,' ,-//.    ,---.      ,  ")
						fmt.Println("       ||---||     ||               o;'   /  ,' /  _  |  /  _  |   ,'/ ")
						fmt.Println("       ||   ||  . .|| .                   |  ''  /  | ''  /  | '.'  / ")
						fmt.Println("_______HH___HH_____||..___________________'____,'___'.__,'___'.__,'  ")
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						time.Sleep(600 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                        ,===:'.,_________'-._   ")
						fmt.Println("                                          ':.'---.__         '-._      ")
						fmt.Println("                                              ':.     '--.         '. ")
						fmt.Println("                                                \\.        '.         '. ")
						fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
						fmt.Println("     __,|**|,______                 (,'     ''\\  \\.   ,--.___'.'     ")
						fmt.Println("    (__ '--'  _--OO__              ,  ,'  ,--.  ', \\.;'         ' ")
						fmt.Println("    |^^|.  ._/     ||              '{*, {    |  :   \\;    ")
						fmt.Println("    |__|    |      ||               |,,'    /  /    //       ")
						fmt.Println("      (--[]--)     ||               |;;    /  ,' ,-//.    ,---.      ,  ")
						fmt.Println("       ||---||. .  ||  .  .         o;'   /  ,' /  _  |  /  _  |   ,'/ ")
						fmt.Println("       ||   ||   . V .                    |  ''  /  | ''  /  | '.'  / ")
						fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						time.Sleep(600 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						fmt.Println("")
						fmt.Println("")
						fmt.Println("                                        ,===:'.,_________'-._   ")
						fmt.Println("                                          ':.'---.__         '-._      ")
						fmt.Println("                                              ':.     '--.         '. ")
						fmt.Println("                                                \\.        '.         '. ")
						fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
						fmt.Println("     __,|**|,__                     (,'     ''\\  \\.   ,--.___'.'     ")
						fmt.Println("    (__ '--'  _)                   ,  ,'  ,--.  ', \\.;'         ' ")
						fmt.Println("    |^^|.  ._/ \\                  '{*, {    |  :   \\;    ")
						fmt.Println("    |__|    |  ||                   |,,'    /  /    //       ")
						fmt.Println("  <===========]OO                   |;;    /  ,' ,-//.    ,---.      ,  ")
						fmt.Println("       ||---||                      o;'   /  ,' /  _  |  /  _  |   ,'/ ")
						fmt.Println("       ||   ||                            |  ''  /  | ''  /  | '.'  / ")
						fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
						fmt.Println("____________________________________________________________________")
						fmt.Println("____________________________________________________________________")
						v.hpactuels_monstre = v.hpactuels_monstre - 16
						fmt.Println("Vous infligez 16 dégats, il ne reste plus que", v.hpactuels_monstre, "points de vie au dragon")
						time.Sleep(2000 * time.Millisecond)
						os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
						m.dragonpattern(v)
					}
				}
			}
			if n == 0 {
				fmt.Println("Vous n'avez pas de boule de feu ou plus assez de mana")
				time.Sleep(1500 * time.Millisecond)
				os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
				v.charturn(m)
			}
		}
	}
	os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
	v.charturn(m)
}
