package main

import (
	"fmt"
	"os"
	"time"
)

func (v *personnage) dragonpattern(m *monstre) {
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                        ,===:'.,_________'-._   ")
	fmt.Println("                                          ':.'---.__         '-._      ")
	fmt.Println("                                              ':.     '--.         '. ")
	fmt.Println("                                                \\.        '.         '. ")
	fmt.Println("       (.--.)                           (,,(,    \\.         '.   ____,-'., ")
	fmt.Println("     __,|**|,__                     (,'     ''\\  \\.   ,--.___'.'     ")
	fmt.Println("    (__ '--'  _)                   ,  ,'  ,--.  ', \\.;'         ' ")
	fmt.Println("    |^^|.  ._/ \\                  '{*, {    |  :   \\;    ")
	fmt.Println("    |__|    |  ||                   |,,'    /  /    //       ")
	fmt.Println("  <===========]OO                   |;;    /  ,' ,-//.    ,---.      ,  ")
	fmt.Println("       ||---||                      o;'   /  ,' /  _  |  /  _  |   ,'/ ")
	fmt.Println("       ||   ||                            |  ''  /  | ''  /  | '.'  / ")
	fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
	fmt.Println("____________________________________________________________________")
	fmt.Println("____________________________________________________________________")
	time.Sleep(600 * time.Millisecond)
	os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                        ,===:'.,_________'-._   ")
	fmt.Println("                                          ':.'---.__         '-._      ")
	fmt.Println("                                              ':.     '--.         '. ")
	fmt.Println("                                                \\.        '.         '. ")
	fmt.Println("       (.--.)                           _(,,(,   \\.         '.   ____,-'., ")
	fmt.Println("     __,|**|,__                   __ __| *   ''\\ \\.   ,--.___'.'     ")
	fmt.Println("    (__ '--'  _)                  o ,''----._ ',   \\.;'         ' ")
	fmt.Println("    |^^|.  ._/ \\                            |  :   \\;    ")
	fmt.Println("    |__|    |  ||                           /  /    //       ")
	fmt.Println("  <===========]OO                          /  ,' ,-//.    ,---.      ,  ")
	fmt.Println("       ||---||                            /  ,' /  _  |  /  _  |   ,'/ ")
	fmt.Println("       ||   ||                            |  ''  /  | ''  /  | '.'  / ")
	fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
	fmt.Println("____________________________________________________________________")
	fmt.Println("____________________________________________________________________")
	time.Sleep(600 * time.Millisecond)
	os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
	fmt.Println("")
	fmt.Println("                                           ,;o")
	fmt.Println("                                           ;;|_________'-._   ")
	fmt.Println("                                          ,''|---.__         '-._      ")
	fmt.Println("                                         }  *}':.     '--.         '. ")
	fmt.Println("                                        ,   \\  \\.        '.         '. ")
	fmt.Println("       (.--.)                          |     \\  \\.         '.   ____,-'., ")
	fmt.Println("     __,|**|,__                        |     '\\  \\.   ,--.___'.'     ")
	fmt.Println("    (__ '--'  _)                       L___--.  ', \\.;'         ' ")
	fmt.Println("    |^^|.  ._/ \\                            |  :   \\;    ")
	fmt.Println("    |__|    |  ||                           /  /    //       ")
	fmt.Println("  <===========]OO                          /  ,' ,-//.    ,---.      ,  ")
	fmt.Println("       ||---||                            /  ,' /  _  |  /  _  |   ,'/ ")
	fmt.Println("       ||   ||                            |  ''  /  | ''  /  | '.'  / ")
	fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
	fmt.Println("____________________________________________________________________")
	fmt.Println("____________________________________________________________________")
	time.Sleep(1200 * time.Millisecond)
	os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                        ,===:'.,_________'-._   ")
	fmt.Println("                                          ':.'---.__         '-._      ")
	fmt.Println("                                              ':.     '--.         '. ")
	fmt.Println("                                                \\.        '.         '. ")
	fmt.Println("       (.--.)                           _(,,(,   \\.         '.   ____,-'., ")
	fmt.Println("     __,|**|,__         ■■■■■■■■■   __|> <   ''\\ \\.   ,--.___'.'     ")
	fmt.Println("    (__ '--'  _)  ■■■■■■■■■■■■■■■■■■O''----._ ',   \\.;'         ' ")
	fmt.Println("    |^^|.  ._/ \\                            |  :   \\;    ")
	fmt.Println("    |__|    |  ||                           /  /    //       ")
	fmt.Println("  <===========]OO                          /  ,' ,-//.    ,---.      ,  ")
	fmt.Println("       ||---||                            /  ,' /  _  |  /  _  |   ,'/ ")
	fmt.Println("       ||   ||                            |  ''  /  | ''  /  | '.'  / ")
	fmt.Println("_______HH___HH____________________________'____,'___'.__,'___'.__,'  ")
	fmt.Println("____________________________________________________________________")
	fmt.Println("____________________________________________________________________")
	time.Sleep(600 * time.Millisecond)
	os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
	fmt.Println("")
	fmt.Println("")
	fmt.Println("                                                ,===:'.,_________'-._   ")
	fmt.Println("                                                  ':.'---.__         '-._      ")
	fmt.Println("                                                      ':.     '--.         '. ")
	fmt.Println("                                                        \\.        '.         '. ")
	fmt.Println(Red+"■■■■■■■■■■■■■■■"+Reset, "                  _(,,(,    \\.         '.   ____,-'., ")
	fmt.Println(Red+"■■■■■■■■■■■■■■■■■■■■■■■"+Reset, "       __|> <   ''\\ \\.   ,--.___'.'     ")
	fmt.Println(Red+"■■■■■■■■■■■■■■■■■■■■■■■■■"+Reset, "     O''----._ ',   \\.;'         ' ")
	fmt.Println(Red+"■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■"+Reset, "       |  :   \\;    ")
	fmt.Println(Red+"■■■■■■■■■■■■■■■■■■■■■■■■■"+Reset, "             /  /    //       ")
	fmt.Println(Red+"■■■■■■■■■■■■■■■■■■■■"+Reset, "                 /  ,' ,-//.    ,---.      ,  ")
	fmt.Println(Red+"■■■■■■■■■■■■■■■■■■"+Reset, "                  /  ,' /  _  |  /  _  |   ,'/ ")
	fmt.Println(Red+"■■■■■■■■■■■■■■■■■"+Reset, "                   |  ''  /  | ''  /  | '.'  / ")
	fmt.Println("_______HH___HH___________________________________'____,'___'.__,'___'.__,'  ")
	fmt.Println("____________________________________________________________________")
	fmt.Println("____________________________________________________________________")
	time.Sleep(1000 * time.Millisecond)
	if m.tour_monstre%3 == 0 {
		v.hpactuels -= 10
	} else {
		v.hpactuels -= 5
	}
	fmt.Println("Le dragon vous attaque,il vous reste", v.hpactuels, "points de vie")
	time.Sleep(1200 * time.Millisecond)
	os.Stdout.WriteString("\x1b[3;J\x1b[H\x1b[2J")
	m.fightersquad(v)
}
